//  "The thought process behind the decision to be a proctologist. Backseat driving and why it benefits all parties on the road. George Washington's fetish for Cherry tree cutting.",
export const speechTopics = [
  `You've discovered your dad, who for years has insisted that you and your friends call him "Doctor", is really just a nurse. Confront him.`,
  "Quantum Physics",
  "Commercial Carpentry with a Class B License",
  "President Grover Cleveland’s impact on industrialization",
  "The Middle East Space Race.",
  "Early 2000s Computer Class Teachers.",
  // "The Safety of hitchhiking before 1936",
  // "The thought process behind the decision to be a proctologist",
  // "Legality of grinding during a junior high school dance",
  // "Backseat driving and why it benefits all parties on the road",
  // "Handicap Bathroom Etiquette",
  // "Do a 45 second stand up comedy bit",
  // "Why abstract art should be outlawed",
  // 'Sparknotes: "Common Sense" by Thomas Paine',
  // "George Washington's fetish for Cherry tree cutting",
  // "Benedict Arnold and why he's a hero from the right pov",
  // "Japanese infantrymen who have yet to admit defeat in WW2",
  // "Espionage as a summer hobby",
  // "Explain the premise of Game of Thrones without spoiling a single plot point",
  // "Pitch a 5 star Californian high school football player, on the University of Buffalo football team",
  // "Give an elevator speech",
  // "The frustration of hyping a funny YouTube video that nobody laughs at",
  // "The art of the bribe and how you can use it, to get what you want for free",
  // "Suing an international company and how it works",
  // "The 2017 Health Care Bill",
  // "Donald Trump's tax returns",
  // "Shorting the housing market in 2008",
  // "The Geneva Convention",
  // "The Yalta Conference and what it got right",
  // "An analysis of the Royal Wedding from a fashion stand point",
  // "The differences between Nazi's and Voldemort's death eaters",
  // 'The rise and fall of the American rock band, "The Eagles"',
  // "Canada's most prized export: Celine Dion",
  // 'The "Titanic" floating door scene',
  // "Squatters Rights",
  // "The French and Indian War",
  // "Any speech by Abraham Lincoln that's not the 'Gettysburg Address'",
  // "Why the concept of taxation with plenty of representation would never have worked in 1776",
  // "Famed trumpeter Myles Davis and his effect on modern pop music",
  // "The advances in modern medicine since 2015",
  // "Why the concubine is a dying industry",
  // "Common courtesy for when you sit shiva at a family friend's house",
  // "The possibility of a Democratic Cuba, in our lifetime",
  // 'The similarities of playing the "Oregon Trail" pc game on its highest difficulty, and the real life Oregon Trail',
  // "How child star, Shirley Temple changed the movie business for the worse",
  // "Employee benefits and Qualified Retirement plans for Santa's elves",
  // "Venture Capitalization and its effect on the civil war",
  // "Topics of conversation at the Last Supper",
  // "Sparknotes: 'Homer's Odyssey'",
  // "The evolution of the market economy in the southern colonies",
  // "The Bay of Pigs and how it all should have went down",
  // "19th century Cash Crops",
];
